"project_identifier" : "youtrackjetbrains"
"api_key_env" : CROWDIN_API_KEY
"base_path_env" : CROWDIN_BASE_PATH

"preserve_hierarchy": true

files: [
 {
  "source" : "/src/app/translations/youtrack-activities-widget.pot",
  "dest": "/widgets/youtrack-activities-widget/youtrack-activities-widget.pot",
  "translation": "/src/app/translations/youtrack-activities-widget_%two_letters_code%.po"
 }
]
